### ISSUE TITLE
Ich habe gewonnen.

### ISSUE THREAD

**Issue by ghost** [Syralist/pixels_flappy#1]
Hi, ich habe Level 3 abgeschlossen.
Nun stürtzt das Spiel ab, oder es gibt einfach keine neuen Levels....

Ich bitte um neue Levels.
Grüße ;D

**Comment by Syralist** [comment]
Öhm, es sind vier Level programmiert. Danach geht es wieder bei 1 los 
nur schneller. So zumindest die Theorie ;)
Ich komme selber nicht so weit, deswegen kann ich das mit dem Absturz 
nicht testen ;D

**Comment by ghost** [comment]
Das Spiel mach unglaublich spaß ;D
